### ISSUE TITLE
kubernetes 1.25 policy/v1beta1/PodSecurityPolicy

### ISSUE THREAD

**Issue by bboysoulcn** [groundcover-com/caretta#57]
the server could not find the requested resource

**Comment by pavellad** [comment]
@bboysoulcn You can disable PodSecurityPolicy using this two values:

```
rbac:
  pspEnabled: 'false'

victoria-metrics-single:
  rbac:
    pspEnabled: 'false'
```
